### ISSUE TITLE
Building Problem

### ISSUE THREAD

**Issue by alexsmartens** [LegendGraphics/regmm#1]
Hi,
I have tried to build regmm, but it does not work out. Could you help to fix this problem, please
Thank you!
I'm having the following error:

$ cmake ..
'-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alex/Downloads/regmm-master/cmake

$ make
Scanning dependencies of target regmm
[ 25%] Building CXX object CMakeFiles/regmm.dir/regmm/3rdparty/tinyobj/tiny_obj_loader.cc.o
[ 50%] Building CXX object CMakeFiles/regmm.dir/regmm/3rdparty/tinyobj/obj_writer.cc.o
[ 75%] Building CXX object CMakeFiles/regmm.dir/regmm/main.cpp.o
In file included from /home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:6:0,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:3:
/home/alex/Downloads/regmm-master/regmm/io/basic_types.hpp:6:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
CMakeFiles/regmm.dir/build.make:110: recipe for target 'CMakeFiles/regmm.dir/regmm/main.cpp.o' failed
make[2]: *** [CMakeFiles/regmm.dir/regmm/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/regmm.dir/all' failed
make[1]: *** [CMakeFiles/regmm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fanxiaochen** [comment]
Hi, 
You need include [Eigen ](http://eigen.tuxfamily.org/index.php?title=Main_Page)  which is a header-only algebra library.

**Comment by alexsmartens** [comment]
I have Eigen installed. 
Should I write a special path for it in regmm or so?

**Comment by BojianWu** [comment]
Actually, you should set an environment variable named EIGEN3_INCLUDE_DIR pointing to your Eigen directory. Or, you can modify CMakeLists.txt (line 6) to change the path manually. Hope this helps.

**Comment by alexsmartens** [comment]
Thank you. This part is solved, now I have another problem
Would you give your suggestion for solving it, please

$ make
Scanning dependencies of target regmm
[ 25%] Building CXX object CMakeFiles/regmm.dir/regmm/3rdparty/tinyobj/tiny_obj_loader.cc.o
[ 50%] Building CXX object CMakeFiles/regmm.dir/regmm/3rdparty/tinyobj/obj_writer.cc.o
[ 75%] Building CXX object CMakeFiles/regmm.dir/regmm/main.cpp.o
In file included from /home/alex/Downloads/regmm-master/regmm/main.cpp:3:0:
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp: In function ‘void regmm::loadMeshObject(const string&, regmm::Mesh<Scalar, Dim>&)’:
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:78:21: error: ‘tinyobj’ was not declared in this scope
         std::vector<tinyobj::shape_t> shapes;
                     ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:78:37: error: template argument 1 is invalid
         std::vector<tinyobj::shape_t> shapes;
                                     ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:78:37: error: template argument 2 is invalid
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:79:21: error: the value of ‘tinyobj’ is not usable in a constant expression
         std::vector<tinyobj::material_t> materials;
                     ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:78:21: note: ‘tinyobj’ was not declared ‘constexpr’
         std::vector<tinyobj::shape_t> shapes;
                     ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:79:40: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
         std::vector<tinyobj::material_t> materials;
                                        ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:79:40: note:   expected a type, got ‘tinyobj’
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:79:40: error: template argument 2 is invalid
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:81:27: error: ‘tinyobj’ is not a class, namespace, or enumeration
         std::string err = tinyobj::LoadObj(shapes, materials, filename.c_str())
                           ^
In file included from /usr/include/c++/5/cassert:43:0,
                 from /home/alex/Downloads/eigen-3.3.3/Eigen/Core:261,
                 from /home/alex/Downloads/regmm-master/regmm/io/basic_types.hpp:6,
                 from /home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:6,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:3:
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:88:23: error: request for member ‘size’ in ‘shapes’, which is of non-class type ‘int’
         assert(shapes.size() == 1 ? true : ("obj should be only one shape" && f
                       ^
In file included from /home/alex/Downloads/regmm-master/regmm/main.cpp:3:0:
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:90:9: error: ‘tinyobj’ is not a class, namespace, or enumeration
         tinyobj::mesh_t& mesh = shapes[0].mesh;
         ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:90:26: error: ‘mesh’ was not declared in this scope
         tinyobj::mesh_t& mesh = shapes[0].mesh;
                          ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:90:41: error: invalid types ‘int[int]’ for array subscript
         tinyobj::mesh_t& mesh = shapes[0].mesh;
                                         ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp: In function ‘void regmm::saveMeshObject(const string&, regmm::Mesh<Scalar, Dim>&)’:
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:112:21: error: ‘tinyobj’ was not declared in this scope
         std::vector<tinyobj::shape_t> out_shape(1);
                     ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:112:37: error: template argument 1 is invalid
         std::vector<tinyobj::shape_t> out_shape(1);
                                     ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:112:37: error: template argument 2 is invalid
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:114:9: error: ‘tinyobj’ is not a class, namespace, or enumeration
         tinyobj::mesh_t& mesh = out_shape[0].mesh;
         ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:114:26: error: ‘mesh’ was not declared in this scope
         tinyobj::mesh_t& mesh = out_shape[0].mesh;
                          ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:114:44: error: invalid types ‘int[int]’ for array subscript
         tinyobj::mesh_t& mesh = out_shape[0].mesh;
                                            ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:141:55: error: there are no arguments to ‘WriteObj’ that depend on a template parameter, so a declaration of ‘WriteObj’ must be available [-fpermissive]
         bool ret = WriteObj(filename, out_shape, false);
                                                       ^
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:141:55: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from /home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:10:0,
                 from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:6,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp: In member function ‘void regmm::ARAP<Scalar, Dim>::buildA()’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:53:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:53:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                          ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:53:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:53:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                               ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:53:79: error: expected primary-expression before ‘,’ token
 APSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::def
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:53:85: error: ‘::deform_model_’ has not been declared
 er<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_mo
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:62:9: error: ‘A_’ was not declared in this scope
         A_.resize(Dim);
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp: In member function ‘void regmm::ARAP<Scalar, Dim>::buildb()’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:96:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:96:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                          ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:96:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:96:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                               ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:96:79: error: expected primary-expression before ‘,’ token
 APSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::def
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:96:85: error: ‘::deform_model_’ has not been declared
 er<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_mo
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:103:9: error: ‘b_’ was not declared in this scope
         b_.resize(ver_num, Dim);
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp: In member function ‘void regmm::ARAP<Scalar, Dim>::initRotation()’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:119:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:119:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                          ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:119:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:119:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                               ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:119:79: error: expected primary-expression before ‘,’ token
 APSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::def
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:119:85: error: ‘::deform_model_’ has not been declared
 er<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_mo
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp: In member function ‘void regmm::ARAP<Scalar, Dim>::updateRotation()’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:134:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:134:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                          ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:134:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:134:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                               ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:134:79: error: expected primary-expression before ‘,’ token
 APSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::def
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:134:85: error: ‘::deform_model_’ has not been declared
 er<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_mo
                                                                     ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:11:0,
                 from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:6,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp: In member function ‘void regmm::DataFitting<Scalar, Dim>::buildA()’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:49:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:49:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                          ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:49:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:49:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                               ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:49:79: error: expected primary-expression before ‘,’ token
 APSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::def
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:49:85: error: ‘::deform_model_’ has not been declared
 er<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_mo
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:57:9: error: ‘A_’ was not declared in this scope
         A_.resize(Dim);
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:63:54: error: expected primary-expression before ‘,’ token
             wi_x += zero_correction(ARAPSolver<Scalar, Dim>::lambda_data_fittin
                                                      ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:63:60: error: ‘::lambda_data_fitting_’ has not been declared
             wi_x += zero_correction(ARAPSolver<Scalar, Dim>::lambda_data_fittin
                                                            ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:11:0,
                 from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:6,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:64:54: error: expected primary-expression before ‘,’ token
             wi_y += zero_correction(ARAPSolver<Scalar, Dim>::lambda_data_fittin
                                                      ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:64:60: error: ‘::lambda_data_fitting_’ has not been declared
             wi_y += zero_correction(ARAPSolver<Scalar, Dim>::lambda_data_fittin
                                                            ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:65:68: error: expected primary-expression before ‘,’ token
             if (Dim == 3) wi_z += zero_correction(ARAPSolver<Scalar, Dim>::lamb
                                                                    ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:65:74: error: ‘::lambda_data_fitting_’ has not been declared
        if (Dim == 3) wi_z += zero_correction(ARAPSolver<Scalar, Dim>::lambda_da
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp: In member function ‘void regmm::DataFitting<Scalar, Dim>::buildb()’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:87:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:87:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                          ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:87:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:87:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar,
                                               ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:87:79: error: expected primary-expression before ‘,’ token
 APSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::def
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:87:85: error: ‘::deform_model_’ has not been declared
 er<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_mo
                                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:94:9: error: ‘b_’ was not declared in this scope
         b_.resize(ver_num, Dim);
         ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:104:42: error: expected primary-expression before ‘,’ token
             b_.row(i) = ARAPSolver<Scalar, Dim>::lambda_data_fitting_*2*cov_mat
                                          ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:104:48: error: ‘::lambda_data_fitting_’ has not been declared
             b_.row(i) = ARAPSolver<Scalar, Dim>::lambda_data_fitting_*2*cov_mat
                                                ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:6:0,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp: In member function ‘void regmm::ARAPSolver<Scalar, Dim>::deforming()’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:250:31: error: there are no arguments to ‘rewriteOriginalSource’ that depend on a template parameter, so a declaration of ‘rewriteOriginalSource’ must be available [-fpermissive]
         rewriteOriginalSource();
                               ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/registrator.hpp:9:0,
                 from /home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_base.hpp:28,
                 from /home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp:32,
                 from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:4,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/io/points.hpp: In instantiation of ‘void regmm::loadPointSet(const string&, typename regmm::PtsType<Scalar, Dim>::Points&) [with Scalar = float; int Dim = 3; std::__cxx11::string = std::__cxx11::basic_string<char>; typename regmm::PtsType<Scalar, Dim>::Points = regmm::Arrays<regmm::Array<float, 3>, float, 3>]’:
/home/alex/Downloads/regmm-master/regmm/main.cpp:25:58:   required from here
/home/alex/Downloads/regmm-master/regmm/io/points.hpp:58:17: error: invalid initialization of non-const reference of type ‘regmm::Array<float, 3>&’ from an rvalue of type ‘regmm::PtType<float, 3>::Point {aka regmm::Array<float, 3>}’
                 ps.push_back(PointType(m_values[3*i], m_values[3*i+1], m_values
                 ^
In file included from /home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:6:0,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:3:
/home/alex/Downloads/regmm-master/regmm/io/basic_types.hpp:117:14: note:   initializing argument 1 of ‘void regmm::Arrays<ArrayType, Scalar, Dim>::push_back(ArrayType&) [with ArrayType = regmm::Array<float, 3>; Scalar = float; int Dim = 3]’
         void push_back(ArrayType& point)
              ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/registrator.hpp:9:0,
                 from /home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_base.hpp:28,
                 from /home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp:32,
                 from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:4,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/io/points.hpp:60:17: error: invalid initialization of non-const reference of type ‘regmm::Array<float, 3>&’ from an rvalue of type ‘regmm::PtType<float, 3>::Point {aka regmm::Array<float, 3>}’
                 ps.push_back(PointType(m_values[2*i], m_values[2*i+1]));
                 ^
In file included from /home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:6:0,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:3:
/home/alex/Downloads/regmm-master/regmm/io/basic_types.hpp:117:14: note:   initializing argument 1 of ‘void regmm::Arrays<ArrayType, Scalar, Dim>::push_back(ArrayType&) [with ArrayType = regmm::Array<float, 3>; Scalar = float; int Dim = 3]’
         void push_back(ArrayType& point)
              ^
In file included from /home/alex/Downloads/regmm-master/regmm/main.cpp:3:0:
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp: In instantiation of ‘void regmm::saveMeshObject(const string&, regmm::Mesh<Scalar, Dim>&) [with Scalar = float; int Dim = 3; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/alex/Downloads/regmm-master/regmm/main.cpp:70:59:   required from here
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:141:28: error: ‘WriteObj’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
         bool ret = WriteObj(filename, out_shape, false);
                            ^
In file included from /home/alex/Downloads/regmm-master/regmm/io/points.hpp:10:0,
                 from /home/alex/Downloads/regmm-master/regmm/transform/registrator.hpp:9,
                 from /home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_base.hpp:28,
                 from /home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp:32,
                 from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:4,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/3rdparty/tinyobj/obj_writer.h:6:13: note: ‘bool WriteObj(const string&, const std::vector<tinyobj::shape_t>&, bool)’ declared here, later in the translation unit
 extern bool WriteObj(const std::string& filename, const std::vector<tinyobj::sh
             ^
In file included from /home/alex/Downloads/regmm-master/regmm/main.cpp:3:0:
/home/alex/Downloads/regmm-master/regmm/io/mesh.hpp:141:28: error: invalid initialization of reference of type ‘const std::vector<tinyobj::shape_t>&’ from expression of type ‘int’
         bool ret = WriteObj(filename, out_shape, false);
                            ^
In file included from /home/alex/Downloads/regmm-master/regmm/io/points.hpp:10:0,
                 from /home/alex/Downloads/regmm-master/regmm/transform/registrator.hpp:9,
                 from /home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_base.hpp:28,
                 from /home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp:32,
                 from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:4,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/3rdparty/tinyobj/obj_writer.h:6:13: note: in passing argument 2 of ‘bool WriteObj(const string&, const std::vector<tinyobj::shape_t>&, bool)’
 extern bool WriteObj(const std::string& filename, const std::vector<tinyobj::sh
             ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:6:0,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp: In instantiation of ‘void regmm::ARAPSolver<Scalar, Dim>::initFittingParas() [with Scalar = float; int Dim = 3]’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:328:25:   required from ‘void regmm::ARAPSolver<Scalar, Dim>::init() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:211:13:   required from ‘void regmm::ARAPSolver<Scalar, Dim>::compute() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:273:13:   required from ‘void regmm::RegmmEngine<Scalar, Dim>::compute() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/main.cpp:66:27:   required from here
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:346:36: error: no type named ‘Zero’ in ‘regmm::MatrixType<float, 3>::Matrix {aka class Eigen::Matrix<float, -1, -1, 1, -1, -1>}’
         deform_model_._data_corres = TCorresMatrix::Zero(this->M_, this->N_);
                                    ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:11:0,
                 from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:6,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp: In instantiation of ‘void regmm::DataFitting<Scalar, Dim>::buildb() [with Scalar = float; int Dim = 3]’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:31:15:   required from ‘void regmm::DataFitting<Scalar, Dim>::build() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:482:9:   required from ‘void regmm::ARAPSolver<Scalar, Dim>::initBuild() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:301:18:   required from ‘Scalar regmm::ARAPSolver<Scalar, Dim>::m_step() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:230:32:   required from ‘void regmm::ARAPSolver<Scalar, Dim>::deform() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:213:15:   required from ‘void regmm::ARAPSolver<Scalar, Dim>::compute() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:273:13:   required from ‘void regmm::RegmmEngine<Scalar, Dim>::compute() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/main.cpp:66:27:   required from here
/home/alex/Downloads/regmm-master/regmm/transform/arap/data_fitting.hpp:98:53: error: no type named ‘Zero’ in ‘regmm::MatrixType<float, 3>::Vector {aka class Eigen::Matrix<float, -1, 1>}’
             TVector weight_cloud = TVector::Zero(Dim);
                                                     ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:10:0,
                 from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:6,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp: In instantiation of ‘void regmm::ARAP<Scalar, Dim>::updateRotation() [with Scalar = float; int Dim = 3]’:
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:40:23:   required from ‘void regmm::ARAP<Scalar, Dim>::projection() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:560:9:   required from ‘void regmm::ARAPSolver<Scalar, Dim>::projection() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:310:23:   required from ‘Scalar regmm::ARAPSolver<Scalar, Dim>::m_step() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:230:32:   required from ‘void regmm::ARAPSolver<Scalar, Dim>::deform() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap_solver.hpp:213:15:   required from ‘void regmm::ARAPSolver<Scalar, Dim>::compute() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:273:13:   required from ‘void regmm::RegmmEngine<Scalar, Dim>::compute() [with Scalar = float; int Dim = 3]’
/home/alex/Downloads/regmm-master/regmm/main.cpp:66:27:   required from here
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:149:16: error: no type named ‘Zero’ in ‘regmm::MatrixType<float, 3>::Matrix {aka class Eigen::Matrix<float, -1, -1, 1, -1, -1>}’
             Di = TMatrix::Zero(adj_list[i].size(), adj_list[i].size());
                ^
/home/alex/Downloads/regmm-master/regmm/transform/arap/arap.hpp:168:51: error: no type named ‘Identity’ in ‘regmm::MatrixType<float, 3>::Matrix {aka class Eigen::Matrix<float, -1, -1, 1, -1, -1>}’
             TMatrix C = TMatrix::Identity(Dim, Dim);
                                                   ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:4:0,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp: In instantiation of ‘void regmm::CPDRigid<Scalar, Dim>::initialization() [with Scalar = float; int Dim = 3]’:
/home/alex/Downloads/regmm-master/regmm/main.cpp:73:1:   required from here
/home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp:124:19: error: no type named ‘Identity’ in ‘regmm::MatrixType<float, 3>::Matrix {aka class Eigen::Matrix<float, -1, -1, 1, -1, -1>}’
         paras_.R_ = TMatrix::Identity(Dim, Dim);
                   ^
/home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp:125:19: error: no type named ‘Zero’ in ‘regmm::MatrixType<float, 3>::Vector {aka class Eigen::Matrix<float, -1, 1>}’
         paras_.t_ = TVector::Zero(Dim, 1);
                   ^
In file included from /home/alex/Downloads/regmm-master/regmm/transform/regmm_engine.hpp:4:0,
                 from /home/alex/Downloads/regmm-master/regmm/main.cpp:4:
/home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp: In instantiation of ‘void regmm::CPDRigid<Scalar, Dim>::e_step() [with Scalar = float; int Dim = 3]’:
/home/alex/Downloads/regmm-master/regmm/main.cpp:73:1:   required from here
/home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp:179:53: error: no type named ‘Zero’ in ‘regmm::MatrixType<float, 3>::Matrix {aka class Eigen::Matrix<float, -1, -1, 1, -1, -1>}’
             TMatrix aX = TMatrix::Zero(this->N_, Dim);
                                                     ^
/home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp: In instantiation of ‘void regmm::CPDRigid<Scalar, Dim>::m_step() [with Scalar = float; int Dim = 3]’:
/home/alex/Downloads/regmm-master/regmm/main.cpp:73:1:   required from here
/home/alex/Downloads/regmm-master/regmm/transform/cpd/cpd_rigid.hpp:208:47: error: no type named ‘Identity’ in ‘regmm::MatrixType<float, 3>::Matrix {aka class Eigen::Matrix<float, -1, -1, 1, -1, -1>}’
         TMatrix C = TMatrix::Identity(Dim, Dim);
                                               ^
CMakeFiles/regmm.dir/build.make:110: recipe for target 'CMakeFiles/regmm.dir/regmm/main.cpp.o' failed
make[2]: *** [CMakeFiles/regmm.dir/regmm/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/regmm.dir/all' failed
make[1]: *** [CMakeFiles/regmm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fanxiaochen** [comment]
I have committed a small fix but I'm not sure whether it can work or not in linux. Besides, you should first compile a dependency library called figtree in regmm/3rdparty/figtree,  and then change the regmm/cmake/Find3rdParty.cmake to the linux version.

**Comment by Luxcy** [comment]
I have done what you said. but still have some bugs. 
see:
[ 14%] Building CXX object CMakeFiles/regmm.dir/regmm/3rdparty/tinyobj/tiny_obj_loader.cc.o
[ 28%] Building CXX object CMakeFiles/regmm.dir/regmm/3rdparty/tinyobj/obj_writer.cc.o
[ 42%] Building CXX object CMakeFiles/regmm.dir/regmm/main.cpp.o
[ 57%] Building CXX object CMakeFiles/regmm.dir/regmm/transform/arap/arap.cpp.o
[ 71%] Building CXX object CMakeFiles/regmm.dir/regmm/transform/arap/arap_solver.cpp.o
[ 85%] Building CXX object CMakeFiles/regmm.dir/regmm/transform/arap/data_fitting.cpp.o
In file included from /home/lux813/Task/regmm-master/regmm/transform/arap/arap_solver.hpp:10:0,
                 from /home/lux813/Task/regmm-master/regmm/transform/regmm_engine.hpp:6,
                 from /home/lux813/Task/regmm-master/regmm/main.cpp:4:
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp: In member function ‘void regmm::ARAP<Scalar, Dim>::buildA()’:
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:57:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
         ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:57:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                          ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:57:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:57:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                               ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:57:79: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                                                               ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:57:85: error: ‘::deform_model_’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                                                                     ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:66:9: error: ‘A_’ was not declared in this scope
         A_.resize(Dim);
         ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp: In member function ‘void regmm::ARAP<Scalar, Dim>::buildb()’:
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:100:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
         ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:100:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                          ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:100:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:100:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                               ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:100:79: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                                                               ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:100:85: error: ‘::deform_model_’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                                                                     ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:107:9: error: ‘b_’ was not declared in this scope
         b_.resize(ver_num, Dim);
         ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp: In member function ‘void regmm::ARAP<Scalar, Dim>::initRotation()’:
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:123:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
         ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:123:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                          ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:123:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:123:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                               ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:123:79: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                                                               ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:123:85: error: ‘::deform_model_’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                                                                     ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp: In member function ‘void regmm::ARAP<Scalar, Dim>::updateRotation()’:
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:138:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
         ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:138:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                          ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:138:32: error: ‘::DeformModel’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:138:47: error: ‘deform_model’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                               ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:138:79: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                                                               ^
/home/lux813/Task/regmm-master/regmm/transform/arap/arap.hpp:138:85: error: ‘::deform_model_’ has not been declared
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
                                                                                     ^
In file included from /home/lux813/Task/regmm-master/regmm/transform/arap/arap_solver.hpp:11:0,
                 from /home/lux813/Task/regmm-master/regmm/transform/regmm_engine.hpp:6,
                 from /home/lux813/Task/regmm-master/regmm/main.cpp:4:
/home/lux813/Task/regmm-master/regmm/transform/arap/data_fitting.hpp: In member function ‘void regmm::DataFitting<Scalar, Dim>::buildA()’:
/home/lux813/Task/regmm-master/regmm/transform/arap/data_fitting.hpp:50:9: error: ‘ARAPSolver’ was not declared in this scope
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;
         ^
/home/lux813/Task/regmm-master/regmm/transform/arap/data_fitting.hpp:50:26: error: expected primary-expression before ‘,’ token
         ARAPSolver<Scalar, Dim>::DeformModel& deform_model = ARAPSolver<Scalar, Dim>::deform_model_;

I think this bug about circular dependency,because arap.hpp depend on arap_solver.hpp,arap_solver.hpp depend on arap.hpp, and data_fitting.hpp depend on arap_solver.hpp, arap_solver.hpp depend on data_fitting.hpp.But I don't resolve it. Can you give me some suggestions?Thank you very much.
(ps : I use ubuntu systems)
